### ISSUE TITLE
Add google search

### ISSUE THREAD

**Issue by nympyx** [victal/quickcommands#17]
It would be great if you could search with google like Vivaldi's search box does

**Comment by victal** [comment]
Hi, thanks for your interest!

I started working on a search feature back when the webextension search API was released but haven't found the time to finish it, so it will be eventually implemented, but only when I can come back to it or if someone drops a PR adding the feature first.

**Comment by victal** [comment]
This took longer than expected, but search using the browser's default search engine (which usually defaults to google and can be changed via about:preferences#search) is available starting from version 1.5.0 of the extension, which should be available in AMO shortly.
