### ISSUE TITLE
Does it support activate extension like Vivaldi does

### ISSUE THREAD

**Issue by snowman** [victal/quickcommands#32]
Press `Enter` to activate extension popup, and open the options page with `Ctrl-Enter` with `Quick Commands`

**Comment by victal** [comment]
No, unfortunately this extension does not support opening popups or option pages for other installed extensions.
 
In fact, from what I read on the MDN docs I think the WebExtensions API does not even provide a way to do that, so it would not be possible (_maybe_ one could use [ExtensionInfo.optionsUrl](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management/ExtensionInfo) to open an extension's options page, though I haven't tested that so I'm not sure - but I found no similar option for extension popups or pages).

**Comment by snowman** [comment]
Thanks, then I consider leave Chrome 🎃
