### ISSUE TITLE
[SUGGESTION] Toolbar button & remember popup windows size

### ISSUE THREAD

**Issue by ghost** [victal/quickcommands#4]
Wow, very nice. Opened tabs, history, bookmarks, all accessible/searchable from one place: this is a must.

I'm aware _quickcommands_ focuses on keyboard users, and alt+shift+R works fine. Yet for toolbar buttons aficionados (not sure I'd mention them if I wern't one of them!) a dedicated button would be welcomed.

The size of _quickcommands_' window is fixed by the extension, having it remember the user's resized preference would be welcomed as well. I think it starts at 600x500, which is small. I have to resize it each time I open it.

Thanks for this fast, smart extension.

**Comment by opes** [comment]
@mazesy I went ahead and added both those things (toolbar icon & saving the window size).

@victal let me know if this looks good to you and if it's something you want to merge.

**Comment by ghost** [comment]
@opes that's great news! Waiting for updated _quickcommands_ on _AMO_ and I'm bound to declare then "You know what? I'm happy"!

**Comment by ghost** [comment]
@opes I hope @victal is still around. If he could at least acknowledge the improvement you're proposing.
Or why not propose yourself to AMO a _quickcommands revised_ with your enhancements, since you seem reactive to suggestions?

**Comment by victal** [comment]
Hi, I'm still around, I just haven't had the time to look at this during the week.

@opes Thanks for the PR, I'll try and take a look.

**Comment by ghost** [comment]
@victal maybe does it appear to be rude when pushing a developer who's doing a fine work, freely and on his free time. And perhaps it is. I just happen to become speedy when fond of something and perceiving what more it may become. My comment wasn't really civilized, excess of enthusiasm, lack of perspective.

We'll wait the time it needs. Thanks for the work already achieved with _quickcommands_.

**Comment by opes** [comment]
@mazesy: Pull request #5 has been reviewed and updated. I made some adjustments as per @victal's comments. The next steps are getting the PR merged and the addon updated on AMO.

**Comment by ghost** [comment]
@opes I appreciate you letting me know how the development of _quickcommands_ is carrying on. Shapes my perspective within an intact enthusiasm. I definitely stay tuned :=)

**Comment by victal** [comment]
Just released version 1.2.0 to AMO, it should be available soon.

**Comment by ghost** [comment]
_quickcommands_ 1.2.0 available on AMO, I've just installed it, great, nice work :=)
